parameters:
#    board_test.example.class: Board\TestBundle\Example

services:
#    board_test.example:
#        class: %board_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
